"use client";

import React, { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Send,
  Bot,
  User,
  ChevronDown,
  Loader2,
  Copy,
  Check,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Message, AgentRole } from "@/types";
import { cn } from "@/lib/utils";
import { formatRelativeTime } from "@/lib/utils";

const MODELS = [
  { id: "gpt-4o", label: "GPT-4o", provider: "OpenAI" },
  { id: "gpt-4-turbo", label: "GPT-4 Turbo", provider: "OpenAI" },
  { id: "claude-3-5-sonnet", label: "Claude 3.5 Sonnet", provider: "Anthropic" },
  { id: "gemini-pro-1.5", label: "Gemini 1.5 Pro", provider: "Google" },
  { id: "llama-3.1-70b", label: "LLaMA 3.1 70B", provider: "Meta" },
];

const AGENT_TYPES: Array<{ value: AgentRole; label: string }> = [
  { value: "orchestrator", label: "🎯 Orchestrator" },
  { value: "code_generator", label: "⚡ Code Generator" },
  { value: "code_reviewer", label: "🔍 Code Reviewer" },
  { value: "debugger", label: "🐛 Debugger" },
  { value: "tester", label: "✅ Tester" },
  { value: "documenter", label: "📝 Documenter" },
  { value: "security_auditor", label: "🛡️ Security Auditor" },
  { value: "devops", label: "🚀 DevOps" },
  { value: "data_analyst", label: "📊 Data Analyst" },
];

const WELCOME_MESSAGE: Message = {
  id: "welcome",
  role: "assistant",
  content:
    "👋 Hello! I'm your AI assistant powered by AIOS. I can help you with code generation, debugging, architecture design, and more. What would you like to work on today?",
  timestamp: new Date().toISOString(),
  model: "gpt-4o",
};

interface ChatPanelProps {
  projectId?: string;
  className?: string;
}

export function ChatPanel({ projectId, className }: ChatPanelProps) {
  const [messages, setMessages] = useState<Message[]>([WELCOME_MESSAGE]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [selectedModel, setSelectedModel] = useState(MODELS[0].id);
  const [selectedAgent, setSelectedAgent] = useState<AgentRole>("code_generator");
  const [showModelDropdown, setShowModelDropdown] = useState(false);
  const [showAgentDropdown, setShowAgentDropdown] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const copyToClipboard = async (text: string, id: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const sendMessage = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = {
      id: `user-${Date.now()}`,
      role: "user",
      content: input.trim(),
      timestamp: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);

    // Streaming simulation
    const assistantId = `assistant-${Date.now()}`;
    const streamingMessage: Message = {
      id: assistantId,
      role: "assistant",
      content: "",
      timestamp: new Date().toISOString(),
      model: selectedModel,
      isStreaming: true,
    };
    setMessages((prev) => [...prev, streamingMessage]);

    const mockResponse = `I understand you want to: "${userMessage.content}"\n\nHere's what I can do:\n\n\`\`\`typescript\n// Generated by AIOS ${selectedAgent}\nconst solution = async () => {\n  // Implementation details\n  console.log("Processing with ${selectedModel}");\n  return { status: "success", data: [] };\n};\n\nexport default solution;\n\`\`\`\n\nThis implementation handles the core requirements. Let me know if you need any modifications!`;

    let i = 0;
    const interval = setInterval(() => {
      if (i < mockResponse.length) {
        const chunk = mockResponse.slice(0, i + 3);
        setMessages((prev) =>
          prev.map((m) =>
            m.id === assistantId ? { ...m, content: chunk, isStreaming: true } : m
          )
        );
        i += 3;
      } else {
        clearInterval(interval);
        setMessages((prev) =>
          prev.map((m) =>
            m.id === assistantId
              ? { ...m, content: mockResponse, isStreaming: false, tokens: 256 }
              : m
          )
        );
        setIsLoading(false);
      }
    }, 20);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const currentModel = MODELS.find((m) => m.id === selectedModel);
  const currentAgent = AGENT_TYPES.find((a) => a.value === selectedAgent);

  return (
    <div
      className={cn(
        "flex flex-col h-full bg-[#080810] border-l border-white/5",
        className
      )}
    >
      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-3 border-b border-white/5 flex-shrink-0">
        <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
          <Sparkles className="w-4 h-4 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-white/90">AI Assistant</p>
          <p className="text-xs text-white/30 truncate">
            {currentAgent?.label} · {currentModel?.label}
          </p>
        </div>
      </div>

      {/* Model/Agent Selectors */}
      <div className="flex gap-2 px-3 py-2 border-b border-white/5 flex-shrink-0">
        {/* Agent Selector */}
        <div className="relative flex-1">
          <button
            onClick={() => {
              setShowAgentDropdown(!showAgentDropdown);
              setShowModelDropdown(false);
            }}
            className="w-full flex items-center justify-between gap-1 px-2.5 py-1.5 bg-white/5 rounded-lg text-xs text-white/60 hover:text-white/80 hover:bg-white/8 transition-colors border border-white/8"
          >
            <span className="truncate">{currentAgent?.label}</span>
            <ChevronDown className="w-3 h-3 flex-shrink-0" />
          </button>
          <AnimatePresence>
            {showAgentDropdown && (
              <motion.div
                initial={{ opacity: 0, y: 4 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 4 }}
                className="absolute top-full left-0 mt-1 w-full z-10 glass-card rounded-lg border border-white/10 shadow-glass-lg overflow-hidden"
              >
                {AGENT_TYPES.map((agent) => (
                  <button
                    key={agent.value}
                    onClick={() => {
                      setSelectedAgent(agent.value);
                      setShowAgentDropdown(false);
                    }}
                    className={cn(
                      "w-full text-left px-3 py-1.5 text-xs transition-colors",
                      selectedAgent === agent.value
                        ? "bg-primary/10 text-primary"
                        : "text-white/60 hover:bg-white/5 hover:text-white/80"
                    )}
                  >
                    {agent.label}
                  </button>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Model Selector */}
        <div className="relative flex-1">
          <button
            onClick={() => {
              setShowModelDropdown(!showModelDropdown);
              setShowAgentDropdown(false);
            }}
            className="w-full flex items-center justify-between gap-1 px-2.5 py-1.5 bg-white/5 rounded-lg text-xs text-white/60 hover:text-white/80 hover:bg-white/8 transition-colors border border-white/8"
          >
            <span className="truncate">{currentModel?.label}</span>
            <ChevronDown className="w-3 h-3 flex-shrink-0" />
          </button>
          <AnimatePresence>
            {showModelDropdown && (
              <motion.div
                initial={{ opacity: 0, y: 4 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 4 }}
                className="absolute top-full left-0 mt-1 w-full z-10 glass-card rounded-lg border border-white/10 shadow-glass-lg overflow-hidden"
              >
                {MODELS.map((model) => (
                  <button
                    key={model.id}
                    onClick={() => {
                      setSelectedModel(model.id);
                      setShowModelDropdown(false);
                    }}
                    className={cn(
                      "w-full text-left px-3 py-1.5 transition-colors",
                      selectedModel === model.id
                        ? "bg-primary/10 text-primary"
                        : "text-white/60 hover:bg-white/5 hover:text-white/80"
                    )}
                  >
                    <p className="text-xs">{model.label}</p>
                    <p className="text-[10px] text-white/30">{model.provider}</p>
                  </button>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message) => (
          <motion.div
            key={message.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className={cn(
              "flex gap-2.5",
              message.role === "user" ? "flex-row-reverse" : "flex-row"
            )}
          >
            <div
              className={cn(
                "w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5",
                message.role === "user"
                  ? "bg-secondary/20 border border-secondary/30"
                  : "bg-primary/10 border border-primary/20"
              )}
            >
              {message.role === "user" ? (
                <User className="w-3.5 h-3.5 text-secondary" />
              ) : (
                <Bot className="w-3.5 h-3.5 text-primary" />
              )}
            </div>

            <div
              className={cn(
                "group max-w-[85%] relative",
                message.role === "user" ? "items-end" : "items-start"
              )}
            >
              <div
                className={cn(
                  "px-3.5 py-2.5 text-sm leading-relaxed",
                  message.role === "user"
                    ? "chat-bubble-user text-white/90"
                    : "chat-bubble-assistant text-white/85"
                )}
              >
                <pre className="whitespace-pre-wrap font-sans text-sm">
                  {message.content}
                  {message.isStreaming && (
                    <span className="inline-block w-0.5 h-4 bg-primary ml-0.5 animate-pulse" />
                  )}
                </pre>
              </div>

              <div
                className={cn(
                  "flex items-center gap-2 mt-1 opacity-0 group-hover:opacity-100 transition-opacity",
                  message.role === "user" ? "justify-end" : "justify-start"
                )}
              >
                <span className="text-[10px] text-white/25">
                  {formatRelativeTime(message.timestamp)}
                </span>
                {message.tokens && (
                  <span className="text-[10px] text-white/25">
                    {message.tokens} tokens
                  </span>
                )}
                <button
                  onClick={() => copyToClipboard(message.content, message.id)}
                  className="text-white/25 hover:text-white/60 transition-colors"
                >
                  {copiedId === message.id ? (
                    <Check className="w-3 h-3 text-green-400" />
                  ) : (
                    <Copy className="w-3 h-3" />
                  )}
                </button>
              </div>
            </div>
          </motion.div>
        ))}

        {isLoading && messages[messages.length - 1]?.role !== "assistant" && (
          <div className="flex gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
              <Bot className="w-3.5 h-3.5 text-primary" />
            </div>
            <div className="chat-bubble-assistant px-3.5 py-2.5">
              <Loader2 className="w-4 h-4 text-primary animate-spin" />
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="flex-shrink-0 p-3 border-t border-white/5">
        <div className="flex items-end gap-2 bg-white/5 border border-white/8 rounded-xl p-2 focus-within:border-primary/30 transition-colors">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask anything... (Shift+Enter for new line)"
            rows={1}
            className="flex-1 bg-transparent text-sm text-white/80 placeholder:text-white/25 resize-none focus:outline-none max-h-32 min-h-[20px]"
            style={{ height: "auto" }}
            onInput={(e) => {
              const target = e.target as HTMLTextAreaElement;
              target.style.height = "auto";
              target.style.height = `${Math.min(target.scrollHeight, 128)}px`;
            }}
          />
          <Button
            onClick={sendMessage}
            disabled={!input.trim() || isLoading}
            size="icon"
            className="w-8 h-8 bg-primary/20 border border-primary/30 hover:bg-primary/30 text-primary flex-shrink-0 rounded-lg"
          >
            {isLoading ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Send className="w-3.5 h-3.5" />
            )}
          </Button>
        </div>
        <p className="text-[10px] text-white/20 mt-1.5 text-center">
          AI responses are generated and may not be accurate
        </p>
      </div>
    </div>
  );
}
